# Generated by Django 5.2.7 on 2025-12-03 12:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_initial'),
        ('setor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUsuarioSetor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('e_responsavel', models.BooleanField(default=False, verbose_name='É Responsável')),
                ('monitor', models.BooleanField(default=False, verbose_name='Monitor')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='campus.campus', verbose_name='Campus')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setor.setor', verbose_name='Setor')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Usuário-Setor',
                'verbose_name_plural': 'historical Usuários-Setores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UsuarioSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('e_responsavel', models.BooleanField(default=False, verbose_name='É Responsável')),
                ('monitor', models.BooleanField(default=False, verbose_name='Monitor')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_setores', to='campus.campus', verbose_name='Campus')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_setores', to='setor.setor', verbose_name='Setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_setores', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário-Setor',
                'verbose_name_plural': 'Usuários-Setores',
                'db_table': 'usuario_setor',
                'ordering': ['usuario', 'setor'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'setor'), name='unique_usuario_setor')],
            },
        ),
    ]
