TURNO_MATUTINO = 'matutino'
TURNO_VESPERTINO = 'vespertino'
TURNO_NOTURNO = 'noturno'
TURNO_INTEGRAL = 'integral'

TURNO_OPCOES = [
    (TURNO_MATUTINO, 'Matutino'),
    (TURNO_VESPERTINO, 'Vespertino'),
    (TURNO_NOTURNO, 'Noturno'),
    (TURNO_INTEGRAL, 'Integral'),
]

FORMA_INGRESSO_VESTIBULAR = 'vestibular'
FORMA_INGRESSO_ENEM = 'enem'
FORMA_INGRESSO_TRANSFERENCIA = 'transferencia'
FORMA_INGRESSO_REINGRESSO = 'reingresso'

FORMA_INGRESSO_OPCOES = [
    (FORMA_INGRESSO_VESTIBULAR, 'Vestibular'),
    (FORMA_INGRESSO_ENEM, 'ENEM/SISU'),
    (FORMA_INGRESSO_TRANSFERENCIA, 'Transferência'),
    (FORMA_INGRESSO_REINGRESSO, 'Reingresso'),
]