# Generated by Django 5.2.7 on 2025-10-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpasswordresetcode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Código de redefinição de senha', 'verbose_name_plural': 'historical Códigos de redefinição de senha'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Código de redefinição de senha', 'verbose_name_plural': 'Códigos de redefinição de senha'},
        ),
        migrations.AlterModelTable(
            name='passwordresetcode',
            table='password_reset_codes',
        ),
    ]
