# Generated by Django 5.2.7 on 2025-12-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contato',
            unique_together={('email', 'usuario'), ('telefone', 'usuario')},
        ),
    ]
