# Generated by Django 5.2.7 on 2025-12-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('usuarios', '0002_alter_contato_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargo.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cargo.cargo', verbose_name='Cargo'),
        ),
    ]
