# Generated by Django 5.2.7 on 2025-12-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_historicalusuario_cargo_usuario_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalusuario',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='ativo',
        ),
    ]
