# Generated by Django 5.2.7 on 2025-12-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsetor',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='setor',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla'),
        ),
    ]
