# Generated by Django 5.2.7 on 2025-12-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0002_historicalsetor_sigla_setor_sigla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsetor',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='setor',
            old_name='is_active',
            new_name='ativo',
        ),
    ]
