# Generated by Django 5.2.7 on 2025-12-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='historicalempresa',
            old_name='is_active',
            new_name='ativo',
        ),
    ]
