# Generated by Django 5.2.7 on 2025-12-03 12:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTerceirizado',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('data_inicio_contrato', models.DateField(verbose_name='Data de Início do Contrato')),
                ('data_fim_contrato', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Contrato')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresa.empresa', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Terceirizado',
                'verbose_name_plural': 'historical Terceirizados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Terceirizado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='terceirizado', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('data_inicio_contrato', models.DateField(verbose_name='Data de Início do Contrato')),
                ('data_fim_contrato', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceirizados', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Terceirizado',
                'verbose_name_plural': 'Terceirizados',
                'db_table': 'terceirizados',
                'ordering': ['usuario__nome'],
            },
        ),
    ]
