# Generated by Django 5.2.7 on 2025-12-03 12:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='servidor', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('data_posse', models.DateField(verbose_name='Data de Posse')),
                ('jornada_trabalho', models.IntegerField(choices=[(20, '20 horas'), (40, '40 horas'), (0, 'Dedicação Exclusiva')], default=40, help_text='Horas semanais (0 = Dedicação Exclusiva)', verbose_name='Jornada de Trabalho')),
                ('padrao', models.CharField(max_length=50, verbose_name='Padrão')),
                ('classe', models.CharField(max_length=50, verbose_name='Classe')),
                ('tipo_servidor', models.CharField(help_text='Ex: Professor, Técnico Administrativo, etc.', max_length=100, verbose_name='Tipo de Servidor')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'servidores',
                'ordering': ['usuario__nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalServidor',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('data_posse', models.DateField(verbose_name='Data de Posse')),
                ('jornada_trabalho', models.IntegerField(choices=[(20, '20 horas'), (40, '40 horas'), (0, 'Dedicação Exclusiva')], default=40, help_text='Horas semanais (0 = Dedicação Exclusiva)', verbose_name='Jornada de Trabalho')),
                ('padrao', models.CharField(max_length=50, verbose_name='Padrão')),
                ('classe', models.CharField(max_length=50, verbose_name='Classe')),
                ('tipo_servidor', models.CharField(help_text='Ex: Professor, Técnico Administrativo, etc.', max_length=100, verbose_name='Tipo de Servidor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Servidor',
                'verbose_name_plural': 'historical Servidores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
