# Generated by Django 5.2.7 on 2025-12-01 17:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aluno', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('ira', models.DecimalField(decimal_places=2, default=0.0, help_text='Índice de Rendimento Acadêmico (0.00 a 10.00)', max_digits=4, verbose_name='IRA')),
                ('forma_ingresso', models.CharField(choices=[('vestibular', 'Vestibular'), ('enem', 'ENEM/SISU'), ('transferencia', 'Transferência'), ('reingresso', 'Reingresso')], default='enem', max_length=20, verbose_name='Forma de Ingresso')),
                ('previsao_conclusao', models.IntegerField(help_text='Ano previsto para conclusão do curso', verbose_name='Previsão de Conclusão')),
                ('aluno_especial', models.BooleanField(default=False, verbose_name='Aluno Especial')),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno'), ('integral', 'Integral')], default='integral', max_length=20, verbose_name='Turno')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ano_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('data_colacao', models.DateField(blank=True, null=True, verbose_name='Data de Colação')),
                ('data_expedicao_diploma', models.DateField(blank=True, null=True, verbose_name='Data de Expedição do Diploma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
                'ordering': ['usuario__nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAluno',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('ira', models.DecimalField(decimal_places=2, default=0.0, help_text='Índice de Rendimento Acadêmico (0.00 a 10.00)', max_digits=4, verbose_name='IRA')),
                ('forma_ingresso', models.CharField(choices=[('vestibular', 'Vestibular'), ('enem', 'ENEM/SISU'), ('transferencia', 'Transferência'), ('reingresso', 'Reingresso')], default='enem', max_length=20, verbose_name='Forma de Ingresso')),
                ('previsao_conclusao', models.IntegerField(help_text='Ano previsto para conclusão do curso', verbose_name='Previsão de Conclusão')),
                ('aluno_especial', models.BooleanField(default=False, verbose_name='Aluno Especial')),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno'), ('integral', 'Integral')], default='integral', max_length=20, verbose_name='Turno')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ano_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('data_colacao', models.DateField(blank=True, null=True, verbose_name='Data de Colação')),
                ('data_expedicao_diploma', models.DateField(blank=True, null=True, verbose_name='Data de Expedição do Diploma')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Aluno',
                'verbose_name_plural': 'historical Alunos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
