# Generated by Django 5.2.7 on 2025-10-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaccountcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Código de verificação de email', 'verbose_name_plural': 'Códigos de verificação de email'},
        ),
        migrations.AlterModelOptions(
            name='historicalemailaccountcode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Código de verificação de email', 'verbose_name_plural': 'historical Códigos de verificação de email'},
        ),
    ]
