# Generated by Django 5.2.7 on 2025-12-01 17:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('empresa', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estagiario', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('carga_horaria', models.IntegerField(help_text='Carga horária semanal do estágio', verbose_name='Carga Horária')),
                ('data_inicio_estagio', models.DateField(verbose_name='Data de Início do Estágio')),
                ('data_fim_estagio', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Estágio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estagiarios', to='curso.curso', verbose_name='Curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estagiarios', to='empresa.empresa', verbose_name='Empresa/Instituição')),
            ],
            options={
                'verbose_name': 'Estagiário',
                'verbose_name_plural': 'Estagiários',
                'db_table': 'estagiarios',
                'ordering': ['usuario__nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEstagiario',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('carga_horaria', models.IntegerField(help_text='Carga horária semanal do estágio', verbose_name='Carga Horária')),
                ('data_inicio_estagio', models.DateField(verbose_name='Data de Início do Estágio')),
                ('data_fim_estagio', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Estágio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('curso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='curso.curso', verbose_name='Curso')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresa.empresa', verbose_name='Empresa/Instituição')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Estagiário',
                'verbose_name_plural': 'historical Estagiários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
