# Generated by Django 5.2.7 on 2025-12-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='HistoricalCargo',
        ),
    ]
