# Generated by Django 5.2.7 on 2025-12-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_delete_cargo_delete_historicalcargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='historicalcampus',
            old_name='is_active',
            new_name='ativo',
        ),
    ]
