# Generated by Django 5.2.7 on 2025-12-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividade', '0001_initial'),
        ('setor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='setor.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='historicalatividade',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalatividade',
            name='setor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setor.setor', verbose_name='Setor'),
        ),
    ]
