USUARIO_STATUS_INATIVO = 0
USUARIO_STATUS_ATIVO = 1
USUARIO_STATUS_SUSPENSO = 2

USUARIO_STATUS_OPCOES = (
    (USUARIO_STATUS_INATIVO, 'Inativo'),
    (USUARIO_STATUS_ATIVO, 'Ativo'),
    (USUARIO_STATUS_SUSPENSO, 'Suspenso'),
)

PERFIL_TIPO_USUARIO = 'user'
PERFIL_TIPO_GESTOR = 'manager'
PERFIL_TIPO_ADMIN = 'admin'

PERFIL_TIPO_OPCOES = (
    (PERFIL_TIPO_USUARIO, 'Usuário'),
    (PERFIL_TIPO_GESTOR, 'Gestor'),
    (PERFIL_TIPO_ADMIN, 'Administrador'),
)

PERFIL_STATUS_INATIVO = 0
PERFIL_STATUS_ATIVO = 1
PERFIL_STATUS_SUSPENSO = 2

PERFIL_STATUS_OPCOES = (
    (PERFIL_STATUS_INATIVO, 'Inativo'),
    (PERFIL_STATUS_ATIVO, 'Ativo'),
    (PERFIL_STATUS_SUSPENSO, 'Suspenso'),
)
