USER_STATUS_INATIVO = 0
USER_STATUS_ATIVO = 1
USER_STATUS_SUSPENSO = 2

USER_STATUS_CHOICES = (
    (USER_STATUS_INATIVO, 'Inativo'),
    (USER_STATUS_ATIVO, 'Ativo'),
    (USER_STATUS_SUSPENSO, 'Suspenso'),
)

PROFILE_TYPE_USER = 'user'
PROFILE_TYPE_MANAGER = 'manager'
PROFILE_TYPE_ADMIN = 'admin'

PROFILE_TYPE_CHOICES = (
    (PROFILE_TYPE_USER, 'Usuário'),
    (PROFILE_TYPE_MANAGER, 'Gestor'),
    (PROFILE_TYPE_ADMIN, 'Administrador'),
)

PROFILE_STATUS_INATIVO = 0
PROFILE_STATUS_ATIVO = 1
PROFILE_STATUS_SUSPENSO = 2

PROFILE_STATUS_CHOICES = (
    (PROFILE_STATUS_INATIVO, 'Inativo'),
    (PROFILE_STATUS_ATIVO, 'Ativo'),
    (PROFILE_STATUS_SUSPENSO, 'Suspenso'),
)
